<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.6 setup script
 * Date: Mon, 27 Mar 2017 01:51:55 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: ff_webpage_test [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'ff_webpage_test';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 8888;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'root';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en_GB';
$cfg['ServerDefault'] = 1;
$cfg['blowfish_secret'] = '\'(?\'q^k}k`t\\Y<)!NR5e,TVNo*-2F,_O';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>